name: Deploy
on:
  push:
    tags:
      - "*"

jobs:
  # This is a separate job so that only deploy-pages has the necessary permissions.
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pdoc
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade wheel
          pip install pdoc
          pip install -r dev_requirements.txt
          pip install -e .

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      # Build documentation into docs/
      - name: Building documentation for github page
        run: pdoc -o docs kiteconnect

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

      - id: deployment
        uses: actions/deploy-pages@v1
